# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Exception-Class-TCF
version:      0.02
version_from: lib/Exception/Class/TCF.pm
installdirs:  site
requires:
    Exception::Class:              1.23

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
